# escape=`
FROM tonyhernandezatms/kibana:windowsservercore-ltsc2016-ES_5.5.3
RUN .\bin\kibana-plugin.bat install https://git.bitsensor.io/front-end/elastalert-kibana-plugin/-/jobs/11753/artifacts/raw/artifact/elastalert-5.5.3-latest.zip