network.host: 0.0.0.0
cluster.name: es-dev
node.name: ${HOSTNAME}

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1

path:
    data: g:\
    logs: l:\